# Generated by Django 5.1.1 on 2024-10-04 09:54

import django.db.models.deletion
import mycloud.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название файла')),
                ('file', models.FileField(upload_to=mycloud.utils.user_directory_path, verbose_name='Сам файл')),
                ('size', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Размер файла, байт')),
                ('data_created', models.PositiveBigIntegerField(default=mycloud.utils.seconds_since_epoch, verbose_name='Дата создания')),
                ('date_download', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Дата крайнего скачивания')),
                ('comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий')),
                ('hash', models.CharField(default=mycloud.utils.generating_uuid, max_length=255, unique=True, verbose_name='Название файла в хэш виде')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
        ),
    ]
